### ISSUE TITLE
No bug, just a little thank you!

### ISSUE THREAD

**Issue by g3n35i5** [mircearoata/SatisfactoryAreaActions#17]
Hello @mircearoata, thank you very much for all your work in the field of Satisfactory Moding! As I can see on the [Trello page](https://trello.com/b/YOudjl6r/area-actions), you are also working on a C++ rewrite of Area Actions, is there a repository for it and can anyone help you with it?

**Comment by mircearoata** [comment]
The c++ rewrite will be pushed to the same repo, but I will push it when it is ready. I finished rewriting the core of it, and a few actions, now I'm making the copy and fill actions, and they work, but there are still a few issues to fix, for example the items on the original belt become invisible until something goes on the copied belt, and I have to test it on more than just 2 storages and a belt

**Comment by g3n35i5** [comment]
All right then, big thank you in advance for that, I'm already looking forward to the release!
