### ISSUE TITLE
Right panel not visible in 121639

### ISSUE THREAD

**Issue by AstinusGH** [mircearoata/SatisfactoryAreaActions#20]
Since the last CS EXP update my right panel has not been visible or interactable.
I've tried version 1.6.4 and 1.6.3.
I have completely removed and re-uninstalled SML and Satisfactory Experimental and EA.

**Comment by mircearoata** [comment]
It is an issue with SML, it doesn't call the init function correctly, so the actions list isn't loaded

**Comment by GenApophis** [comment]
So is there a fix or how do i fix that?

**Comment by mircearoata** [comment]
Not something you can do, but I'll try to fix it today

**Comment by MunchyG** [comment]
I have same issue

**Comment by mircearoata** [comment]
SML 2.1.2 was released, which fixes this
