### ISSUE TITLE
Signature error in log

### ISSUE THREAD

**Issue by joelclark** [mircearoata/SatisfactoryAreaActions#3]
_LogPakFile: Display: Found Pak file ../../../FactoryGame/Content/Paks/AreaActions.pak attempting to mount.
LogPakFile: Display: Mounting pak file ../../../FactoryGame/Content/Paks/AreaActions.pak.
LogPakFile: Warning: Pak chunk signing mismatch on chunk [42/222781]! Expected 0xBAA387DC, Received 0x1E3B68F6
LogPakFile: Warning: Pak file has been corrupted or tampered with!_

I can't seem to make this work and I am wondering if this is the cause?

Version 1.6

**Comment by mircearoata** [comment]
That is completely normal, becasue the engine warns that the pak is not from Coffee Stain, which is true.

Do you see the unlock in HUB Tier 0 (you might have to scroll to the right if you have many mods)?

**Comment by joelclark** [comment]
Yeah, I got it working eventually.  I didn't realize you had to craft and equip it to get it to work.  Thanks for making a great mod!  Totally changes how one can think about building at scale.  Cheers!
