### ISSUE TITLE
is there a way to add different modded building to the recipe menu .

### ISSUE THREAD

**Issue by Obimook** [mircearoata/SatisfactoryAreaActions#34]
I was wondering how to add the mk.2-4 mods to support mass recipe set

**Comment by mircearoata** [comment]
You can't, because it's a bug. It was supposed to work with those buildings too, since their building classes are children of the original building class, but I did that wrong. Area Actions 2.0 fixes that

**Comment by Obimook** [comment]
Thank you for your input. Just installed the beta and wow is it an improvement
