### ISSUE TITLE
All menues are impossible to interact after alt-tab

### ISSUE THREAD

**Issue by vyachesIavskiy** [mircearoata/SatisfactoryAreaActions#7]
I believe it's because ALT is currently using for fly lower, but after I switch to another app with alt-tab and them come back to game by clicking the icon or alt-tab, all the game menues are not responsive. I cannot select anything inside my inventory, or storage, main menu is non responsive as well so I cannot even save a game. And there is no exit if you open main menu, you cannot even close it even with ESC key

**Comment by mircearoata** [comment]
That's an issue with the game, you can see if you click somewhere it will create pings which are triggered by alt+click, so it means that the alt key is stuck. It gets unstuck if you press it again

**Comment by VyacheslavNagornyak** [comment]
Tried pressing alt, or every other key, didn’t help

**Comment by mircearoata** [comment]
Can you provide a video for this? I have been trying to reproduce the issue without success

**Comment by VyacheslavNagornyak** [comment]
@mircearoata damn, just couple of hours ago I had this issue where I could not leave main menu again, if I will struggle with this again, I'll record
